jenkins:
  systemMessage: "This Jenkins Instance is managed by CSYE7125 Fall2023 Group 7 Students"
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "123456"
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:admin"
        - "Overall/Read:authenticated" 

credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope: GLOBAL
              id: github_token
              username: ${GITHUB_USERNAME}
              password: ${GITHUB_CREDS}
              description: "Github token for Jenkins"
          
          - usernamePassword:
              scope: GLOBAL
              id: quay_token
              username: ${QUAY_USERNAME}
              password: ${QUAY_CREDS}
              description: "Quay token for Jenkins"

jobs:
  - file: /var/lib/jenkins/multibranch-pipeline.groovy