name: AMI Creation

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: ami-creation

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Setup packer
        uses: hashicorp/setup-packer@main
        with:
          version: '1.8.x'

      - name: Packer init
        run: packer init ./packer/ami.pkr.hcl

      - name: Packer build
        run: packer build -var "GH_USERNAME=${{ vars.GH_USERNAME }}" -var "GH_CREDS=${{ secrets.GH_CREDS }}" -var "QUAY_USERNAME=${{ vars.QUAY_USERNAME }}" -var "QUAY_CREDS=${{ secrets.QUAY_CREDS }}" ./packer/ami.pkr.hcl